<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ProjectStatus</AssemblyName>
    <RootNamespace>ProjectStatus.Client</RootNamespace>
    <Version>0.1.1</Version>
    <ApplicationIcon>Assets\project_status.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
</Project>
